language: php

notifications:
    email: elfimov@gmail.com

install:
  - composer update --prefer-dist --no-interaction --no-scripts --no-progress

script:
  - composer run-script test

after_success:
  - bash <(curl -s https://codecov.io/bash)
